# Generated by Django 3.0.9 on 2020-08-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.PositiveSmallIntegerField()),
                ('availability', models.BooleanField(default=0)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Rooms'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
