# Generated by Django 3.0.9 on 2020-08-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200804_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('price', models.PositiveSmallIntegerField()),
                ('availability', models.BooleanField(default=0)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Room'),
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
