# Generated by Django 3.0.9 on 2020-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200804_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
