# Generated by Django 3.0.9 on 2020-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200804_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_no', 'Date')},
        ),
    ]
